
package org.henry.webservice.soap.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0-M3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MySOAPEndpointService", targetNamespace = "http://soap.webservice.henry.org/", wsdlLocation = "http://localhost:8080/java-ee-webservices/MySOAPEndpointService?wsdl")
public class MySOAPEndpointService
    extends Service
{

    private final static URL MYSOAPENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYSOAPENDPOINTSERVICE_EXCEPTION;
    private final static QName MYSOAPENDPOINTSERVICE_QNAME = new QName("http://soap.webservice.henry.org/", "MySOAPEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/java-ee-webservices/MySOAPEndpointService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYSOAPENDPOINTSERVICE_WSDL_LOCATION = url;
        MYSOAPENDPOINTSERVICE_EXCEPTION = e;
    }

    public MySOAPEndpointService() {
        super(__getWsdlLocation(), MYSOAPENDPOINTSERVICE_QNAME);
    }

    public MySOAPEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYSOAPENDPOINTSERVICE_QNAME, features);
    }

    public MySOAPEndpointService(URL wsdlLocation) {
        super(wsdlLocation, MYSOAPENDPOINTSERVICE_QNAME);
    }

    public MySOAPEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYSOAPENDPOINTSERVICE_QNAME, features);
    }

    public MySOAPEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MySOAPEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MySOAPEndpoint
     */
    @WebEndpoint(name = "MySOAPEndpointPort")
    public MySOAPEndpoint getMySOAPEndpointPort() {
        return super.getPort(new QName("http://soap.webservice.henry.org/", "MySOAPEndpointPort"), MySOAPEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns MySOAPEndpoint
     */
    @WebEndpoint(name = "MySOAPEndpointPort")
    public MySOAPEndpoint getMySOAPEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.webservice.henry.org/", "MySOAPEndpointPort"), MySOAPEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSOAPENDPOINTSERVICE_EXCEPTION!= null) {
            throw MYSOAPENDPOINTSERVICE_EXCEPTION;
        }
        return MYSOAPENDPOINTSERVICE_WSDL_LOCATION;
    }

}
